#!/usr/bin/env bash

# Install drivers
#brew install --cask logitech-options
#brew install --cask logitech-control-center
#brew install --cask logi-options-plus
brew install --cask blackhole-2ch

# Install fonts
brew install --cask font-hack
brew install --cask font-hack-nerd-font
brew install --cask font-fira-code
#brew install --cask font-firacode-nerd-font
#brew install --cask font-firacode-nerd-font-mono
brew install --cask font-fira-mono-for-powerline
brew install --cask font-inter
brew install --cask font-fontawesome
brew install --cask font-open-sans font-open-sans-condensed
brew install --cask font-yanone-kaffeesatz
#brew install --cask font-blokk
brew install --cask font-overpass
brew install --cask font-3270-nerd-font
brew install --cask font-powerline-symbols

# Install text editors
brew install --cask visual-studio-code
#brew install --cask phpstorm
#brew install --cask sublime-text

# Install git clients
brew install --cask github
brew install --cask sublime-merge
brew install --cask sourcetree
brew install --cask gitkraken

# Install general apps
brew install --cask lulu
brew install --cask raycast
brew install --cask numi
brew install --cask zulu
brew install --cask hiddenbar
brew install --cask airtable
#brew install --cask arq
brew install --cask appcleaner
brew install --cask audacity
brew install --cask keepingyouawake
brew install --cask caffeine
#brew install --cask dropbox
#brew install --cask firefox
#brew install --cask flux
brew install --cask komanda
brew install --cask mac2imgur
#brew install --cask macdown
brew install --cask google-chrome
brew install --cask tor-browser
#brew install --cask google-drive
#brew install --cask google-drive-file-stream
brew install --cask zoom
brew install --cask slack
#brew install --cask skype
brew install --cask spotify
#brew install --cask microsoft-office
#brew install --cask spotifree
brew install --cask steam
brew install --cask transmission
brew install --cask vlc
brew install --cask the-unarchiver
brew install --cask typora
brew install --cask notion
brew install --cask todoist
brew install --cask linear-linear
brew install --cask unrarx
brew install --cask carbon-copy-cloner superduper
brew install --cask discord
brew install --cask whatsapp
brew install --cask kodi
brew install --cask sketch
#brew install --cask diffmerge
brew install --cask meld
#brew install --cask sage
brew install --cask fanny
#brew install --cask zotero
#brew install --cask daisydisk
brew install --cask chrome-remote-desktop-host
brew install --cask battle-net
brew install --cask 1password 1password-cli
brew install --cask mendeley
#brew install --cask handbrake
#brew install --cask alfred
brew install --cask hdhomerun
brew install --cask home-assistant
#brew install --cask plex-media-server
brew install --cask plex-media-player
brew install --cask mediainfo
brew install --cask caption
#brew install --cask thinkorswim
brew install --cask balenaetcher
#brew install --cask imaging-edge
brew install --cask gifox
#brew install --cask wine-stable
brew install --cask telegram
brew install --cask xscope
brew install --cask kap
brew install --cask obs
#brew install --cask ishowu
brew install --cask parsehub
brew install --cask raspberry-pi-imager
#brew install --cask mounty

# Install VPN apps
brew install --cask aws-vpn-client
#brew install --cask qv2ray
#brew install --cask v2rayx
#brew install --cask outline-manager
#brew install --cask shadowsocksx
#brew install --cask shadowsocksx-ng

# Install dev apps
brew install --cask brewservicesmenubar
brew install --cask devdocs
brew install --cask phpmon
brew install --cask iconizer
brew install --cask chromedriver
brew install --cask mysqlworkbench
#brew install --cask launchrocket
brew install --cask ksdiff
brew install --cask chrome-devtools
brew install --cask cakebrew
brew install --cask fontplop
brew install --cask gas-mask
brew install --cask imagealpha imageoptim
brew install --cask integrity
brew install --cask impactor
brew install --cask iterm2
brew install --cask warp
brew install --cask insomnia
brew install --cask istumbler
brew install --cask jewelrybox
brew install --cask kitematic
brew install --cask pusher
brew install --cask shuttle
#brew install --cask vagrant
#brew install --cask vagrant-manager
brew install --cask utm
#brew install --cask virtualbox
#brew install --cask cyberduck
brew install --cask royal-tsx
brew install --cask bitbar
brew install --cask psequel
brew install --cask hyper
brew install --cask ngrok
#brew install --cask cactus
#brew install --cask datagrip
#brew install --cask burp-suite
brew install --cask gitify
brew install --cask docker
brew install --cask nucleo
brew install --cask postman
brew install --cask hopper-disassembler
brew install --cask upterm
brew install --cask tabula
#brew install --cask medis
#brew install --cask rdm
brew install --cask tableplus
brew install --cask sequel-ace
brew install --cask hex-fiend
brew install --cask borgbackup
brew install --cask synologyassistant
brew install --cask google-cloud-sdk
#brew install --cask chronograf
brew install --cask mongodb-compass
brew install --cask ray
brew install --cask tinkerwell
brew install --cask hammerspoon
brew install --cask sqlectron
brew install --cask robo-3t

# Install design apps
#brew install --cask avocode
brew install --cask skitch

# Install networking apps
brew install --cask angry-ip-scanner
brew install --cask tunnelblick
#brew install --cask wireshark
