#!/usr/bin/env bash

# Install general libraries
npm install -g yarn
npm install -g pageres
npm install -g peerflix
npm install -g toxy
npm install -g webtorrent
npm install -g localtunnel
npm install -g http-server
npm install -g hostile
npm install -g tldr
npm install -g gifify
npm install -g chrome-remote-interface

# Install dev tools
npm install -g gulp
npm install -g api-benchmark
npm install -g request
npm install -g underscore
npm install -g open
npm install -g supervisor
npm install -g nodemon
npm install -g forever
npm install -g express-generator
npm install -g requirejs
#npm install -g bower
npm install -g grunt-cli
npm install -g imageoptim-cli
npm install -g ios-sim
npm install -g jshint
npm install -g node-inspector
npm install -g nodewebkit
npm install -g rtail
npm install -g how2
npm install -g chalk
npm install -g less
npm install -g node-sass
npm install -g lighthouse
npm install -g hpm-cli
npm install -g electron
npm install -g @vue/cli
